name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ec2-user-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

  deploy_to_nexus:
    needs: build
    runs-on: ec2-user-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy Artifacts to Nexus
      run: ./gradlew publish
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  deploy_to_production:
    needs: deploy_to_nexus
    runs-on: ec2-user-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your production deployment script here
